"""no_constraint

Revision ID: 7033105f1d6f
Revises: a970a02afdca
Create Date: 2025-04-15 21:42:15.192123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7033105f1d6f'
down_revision: Union[str, None] = 'a970a02afdca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_object_name_object_table_model_id', 'nodes', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_object_name_object_table_model_id', 'nodes', ['object_name', 'object_table', 'model_id'])
    # ### end Alembic commands ###
