"""update

Revision ID: 54f0d8b0b486
Revises: 4feea5ff15f3
Create Date: 2024-11-27 01:23:44.526966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54f0d8b0b486'
down_revision: Union[str, None] = '4feea5ff15f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nodes', 'object_table',
               existing_type=postgresql.ENUM('RESOURCES', 'RESOURCE_TYPES', 'FUNCTIONS', 'TEMPLATES', 'TEMPLATE_USAGES', name='tabletype'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nodes', 'object_table',
               existing_type=sa.String(),
               type_=postgresql.ENUM('RESOURCES', 'RESOURCE_TYPES', 'FUNCTIONS', 'TEMPLATES', 'TEMPLATE_USAGES', name='tabletype'),
               existing_nullable=False)
    # ### end Alembic commands ###
