"""update

Revision ID: 8b77abb2a630
Revises: e8ccdac846dc
Create Date: 2025-01-13 13:46:41.885229

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8b77abb2a630'
down_revision: Union[str, None] = 'e8ccdac846dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'model_id', name='uix_import_name_model_id')
    )
    op.create_table('packages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('alias', sa.String(), nullable=True),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias', 'import_id', name='uix_package_alias_import_id'),
    sa.UniqueConstraint('name', 'import_id', name='uix_package_name_import_id')
    )
    op.drop_constraint('models_name_key', 'models', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('models_name_key', 'models', ['name'])
    op.drop_table('packages')
    op.drop_table('imports')
    # ### end Alembic commands ###
