"""add_value

Revision ID: aee96eb3b535
Revises: ec1258d8acdd
Create Date: 2025-01-13 17:02:24.086372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aee96eb3b535'
down_revision: Union[str, None] = 'ec1258d8acdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_attributes', sa.Column('value', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource_attributes', 'value')
    # ### end Alembic commands ###
