"""delete_value

Revision ID: ec1258d8acdd
Revises: 8b77abb2a630
Create Date: 2025-01-13 17:01:48.549186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec1258d8acdd'
down_revision: Union[str, None] = '8b77abb2a630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource_attributes', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_attributes', sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
